### ISSUE TITLE
Flakey spec

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#1190]
## 📋 Summary
```
  1 failing

  1) Signup
       an existing user tries to sign up with the same data
         duplicate email
           returns an error:
     AssertionError: Timed out retrying after 10000ms: Expected to find content: 'Email has already been taken' within the element: <div> but never did.
      at Context.eval (http://localhost:5017/__cypress/tests?p=cypress/integration/signup.spec.js:150452:75)
```
and
```
 1 failing

  1) Signup
       an existing user tries to sign up with the same data
         duplicate phone
           returns an error:
     AssertionError: Timed out retrying after 10000ms: Expected to find content: 'Phone number has already been taken' within the element: <div> but never did.
      at Context.eval (http://localhost:5017/__cypress/tests?p=cypress/integration/signup.spec.js:150444:82)
```
have been flaking lately

**Comment by katelovescode** [comment]
This spec doesn't seem to be failing anymore, so I closed this ticket
