### ISSUE TITLE
Performance - `family_fee` - 65 calls - 2.9s - 100% of calls are slow

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#2495]
In single profile example, these 65 calls were responsible for 2.9s of the request, and 100% of the calls of this method were above the double-digit mark of milliseconds.

Executing action: case_list_for_dashboard — 59.40 ms
```
app/models/nebraska/dashboard_case.rb:63:in `block in family_fee'
app/models/nebraska/dashboard_case.rb:60:in `family_fee'
app/models/nebraska/dashboard_case.rb:32:in `block in attendance_risk'
app/models/nebraska/dashboard_case.rb:26:in `attendance_risk'
app/controllers/api/v1/users_controller.rb:51:in `nebraska_dashboard'
app/controllers/api/v1/users_controller.rb:26:in `case_list_for_dashboard'
app/controllers/application_controller.rb:51:in `collect_metrics'

SELECT "children".* FROM "children" INNER JOIN "child_approvals" ON "children"."id" = "child_approvals"."child_id" WHERE "child_approvals"."approval_id" = $1;
```

**Comment by rebeccakarasiktw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Top 6 offenders for Performance Improvements](https://trello.com/c/9ubTm6cU/15-top-6-offenders-for-performance-improvements)
