### ISSUE TITLE
Performance - `hourly_rate` - 80 calls - 1.66s - 98.75% of calls are slow

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#2497]
In single profile example, these 80 calls were responsible for 1.66s of the request, and 98.75% of the calls of this method were above the double-digit mark of milliseconds.

Executing action: case_list_for_dashboard — 19.10 ms
```
app/services/nebraska/daily/revenue_calculator.rb:47:in `hourly_rate'
app/services/nebraska/daily/revenue_calculator.rb:42:in `ne_base_revenue'
app/services/nebraska/daily/revenue_calculator.rb:25:in `calculate_earned_revenue'
app/services/nebraska/daily/revenue_calculator.rb:19:in `call'
app/models/nebraska/calculated_service_day.rb:25:in `earned_revenue'
app/models/nebraska/dashboard_case.rb:294:in `map'
app/models/nebraska/dashboard_case.rb:294:in `block in scheduled_month_days_revenue'
app/models/nebraska/dashboard_case.rb:290:in `scheduled_month_days_revenue'
app/models/nebraska/dashboard_case.rb:103:in `block in scheduled_revenue'
app/models/nebraska/dashboard_case.rb:99:in `scheduled_revenue'
app/models/nebraska/dashboard_case.rb:33:in `block in attendance_risk'
app/models/nebraska/dashboard_case.rb:26:in `attendance_risk'
app/controllers/api/v1/users_controller.rb:51:in `nebraska_dashboard'
app/controllers/api/v1/users_controller.rb:26:in `case_list_for_dashboard'
app/controllers/application_controller.rb:51:in `collect_metrics'

SELECT "nebraska_rates".* FROM "nebraska_rates" WHERE (effective_on <= '2022-05-01 04:59:59.999999') AND (expires_on is null or expires_on > '2022-04-01 05:00:00') AND "nebraska_rates"."school_age" = $1 AND (max_age >= 33 OR max_age IS NULL) AND "nebraska_rates"."region" = $2 AND "nebraska_rates"."license_type" = $3 AND "nebraska_rates"."accredited_rate" = $4 ORDER BY max_age ASC NULLS LAST;
```

**Comment by rebeccakarasiktw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Top 6 offenders for Performance Improvements](https://trello.com/c/9ubTm6cU/15-top-6-offenders-for-performance-improvements)
