### ISSUE TITLE
Performance - `attendances_this_month` - 145 calls - 3.71s - 93.79% of calls are slow

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#2498]
In single profile example, these 145 calls were responsible for 3.71s of the request, and 93.79% of the calls of this method were above the double-digit mark of milliseconds.

Executing action: case_list_for_dashboard — 12.30 ms
```
app/models/nebraska/dashboard_case.rb:272:in `block in attendances_this_month'
app/models/nebraska/dashboard_case.rb:268:in `attendances_this_month'
app/models/nebraska/dashboard_case.rb:411:in `block in attended_and_absent_dates'
app/models/nebraska/dashboard_case.rb:407:in `attended_and_absent_dates'
app/models/nebraska/dashboard_case.rb:401:in `block (2 levels) in estimated_month_days'
app/models/nebraska/dashboard_case.rb:395:in `select'
app/models/nebraska/dashboard_case.rb:395:in `block in estimated_month_days'
app/models/nebraska/dashboard_case.rb:389:in `estimated_month_days'
app/models/nebraska/dashboard_case.rb:303:in `block in estimated_month_days_revenue'
app/models/nebraska/dashboard_case.rb:299:in `estimated_month_days_revenue'
app/models/nebraska/dashboard_case.rb:89:in `block in estimated_revenue'
app/models/nebraska/dashboard_case.rb:85:in `estimated_revenue'
app/models/nebraska/dashboard_case.rb:34:in `block in attendance_risk'
app/models/nebraska/dashboard_case.rb:26:in `attendance_risk'
app/controllers/api/v1/users_controller.rb:51:in `nebraska_dashboard'
app/controllers/api/v1/users_controller.rb:26:in `case_list_for_dashboard'
app/controllers/application_controller.rb:51:in `collect_metrics'

SELECT DISTINCT "service_days"."id" AS t0_r0, "service_days"."date" AS t0_r1, "service_days"."child_id" AS t0_r2, "service_days"."created_at" AS t0_r3, "service_days"."updated_at" AS t0_r4, "service_days"."total_time_in_care" AS t0_r5, "service_days"."earned_revenue_cents" AS t0_r6, "service_days"."earned_revenue_currency" AS t0_r7, "service_days"."schedule_id" AS t0_r8, "attendances_service_days"."id" AS t1_r0, "attendances_service_days"."check_in" AS t1_r1, "attendances_service_days"."check_out" AS t1_r2, "attendances_service_days"."time_in_care" AS t1_r3, "attendances_service_days"."created_at" AS t1_r4, "attendances_service_days"."updated_at" AS t1_r5, "attendances_service_days"."child_approval_id" AS t1_r6, "attendances_service_days"."wonderschool_id" AS t1_r7, "attendances_service_days"."absence" AS t1_r8, "attendances_service_days"."deleted_at" AS t1_r9, "attendances_service_days"."service_day_id" AS t1_r10 FROM "service_days" INNER JOIN "attendances" ON "service_days"."id" = "attendances"."service_day_id" INNER JOIN "attendances" "attendances_service_days" ON "attendances_service_days"."service_day_id" = "service_days"."id" WHERE "attendances"."child_approval_id" = $1 AND "attendances"."absence" IS NULL;
```

**Comment by rebeccakarasiktw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Top 6 offenders for Performance Improvements](https://trello.com/c/9ubTm6cU/15-top-6-offenders-for-performance-improvements)
