### ISSUE TITLE
Performance - `active_approval` - 3 trace frames - 28 calls - 4.49s - 96.43% of calls are slow

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#2501]
In single profile example, these 28 calls were responsible for 4.49s of the request, and 96.43% of the calls of this method were above the double-digit mark of milliseconds.

Executing action: case_list_for_dashboard — 217.90 ms
```
app/models/child.rb:81:in `active_approval'
app/models/child.rb:85:in `active_child_approval'
app/blueprints/child_blueprint.rb:46:in `block (2 levels) in '
app/controllers/api/v1/users_controller.rb:51:in `nebraska_dashboard'
app/controllers/api/v1/users_controller.rb:26:in `case_list_for_dashboard'
app/controllers/application_controller.rb:51:in `collect_metrics' 

SELECT "approvals".* FROM "approvals" INNER JOIN "child_approvals" ON "approvals"."id" = "child_approvals"."approval_id" WHERE "child_approvals"."child_id" = $1 AND "approvals"."effective_on" <= $2 AND ("approvals"."expires_on" IS NULL OR "approvals"."expires_on" >= $3) ORDER BY "approvals"."updated_at" DESC LIMIT $4;
```

```
app/models/child.rb:85:in `active_child_approval'
app/blueprints/child_blueprint.rb:46:in `block (2 levels) in '
app/controllers/api/v1/users_controller.rb:51:in `nebraska_dashboard'
app/controllers/api/v1/users_controller.rb:26:in `case_list_for_dashboard'
app/controllers/application_controller.rb:51:in `collect_metrics'

SELECT "child_approvals".* FROM "child_approvals" WHERE "child_approvals"."approval_id" = $1 AND "child_approvals"."child_id" = $2 LIMIT $3;
```
```
app/models/nebraska/dashboard_case.rb:261:in `block in absences_this_month'
app/models/nebraska/dashboard_case.rb:257:in `absences_this_month'
app/models/nebraska/dashboard_case.rb:422:in `block in reimbursable_absent_service_days'
app/models/nebraska/dashboard_case.rb:418:in `reimbursable_absent_service_days'
app/models/nebraska/dashboard_case.rb:22:in `initialize'
app/blueprints/child_blueprint.rb:49:in `new'
app/blueprints/child_blueprint.rb:49:in `block (2 levels) in '
app/controllers/api/v1/users_controller.rb:51:in `nebraska_dashboard'
app/controllers/api/v1/users_controller.rb:26:in `case_list_for_dashboard'
app/controllers/application_controller.rb:51:in `collect_metrics'

SELECT DISTINCT "service_days"."id" AS t0_r0, "service_days"."date" AS t0_r1, "service_days"."child_id" AS t0_r2, "service_days"."created_at" AS t0_r3, "service_days"."updated_at" AS t0_r4, "service_days"."total_time_in_care" AS t0_r5, "service_days"."earned_revenue_cents" AS t0_r6, "service_days"."earned_revenue_currency" AS t0_r7, "service_days"."schedule_id" AS t0_r8, "attendances_service_days"."id" AS t1_r0, "attendances_service_days"."check_in" AS t1_r1, "attendances_service_days"."check_out" AS t1_r2, "attendances_service_days"."time_in_care" AS t1_r3, "attendances_service_days"."created_at" AS t1_r4, "attendances_service_days"."updated_at" AS t1_r5, "attendances_service_days"."child_approval_id" AS t1_r6, "attendances_service_days"."wonderschool_id" AS t1_r7, "attendances_service_days"."absence" AS t1_r8, "attendances_service_days"."deleted_at" AS t1_r9, "attendances_service_days"."service_day_id" AS t1_r10 FROM "service_days" INNER JOIN "attendances" ON "service_days"."id" = "attendances"."service_day_id" INNER JOIN "attendances" "attendances_service_days" ON "attendances_service_days"."service_day_id" = "service_days"."id" WHERE "attendances"."child_approval_id" = $1 AND "attendances"."absence" IS NOT NULL;
```

**Comment by rebeccakarasiktw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Top 6 offenders for Performance Improvements](https://trello.com/c/9ubTm6cU/15-top-6-offenders-for-performance-improvements)
