### ISSUE TITLE
Flaky Test children API #case_list_for_dashboard

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#694]
## 📋 Summary
This tests fails flakily!  No kid should be entered without a current child approval so either our tests or factories are set up incorrectly.

```
Randomized with seed 8609
..................................................F...............................................................................................................................................................................

Failures:

  1) children API #case_list_for_dashboard /api/v1/case_list_for_dashboard get admin user active cases found returns a 200 response
     Failure/Error: @child.current_child_approval.update!(subsidy_rule: subsidy_rule)

     NoMethodError:
       undefined method `update!' for nil:NilClass
     # ./app/services/subsidy_rule_associator.rb:31:in `illinois_subsidy_rule_associator'
     # ./app/services/subsidy_rule_associator.rb:19:in `associate_subsidy_rule'
     # ./app/services/subsidy_rule_associator.rb:13:in `call'
     # ./app/models/child.rb:65:in `associate_subsidy_rule'
     # ./spec/requests/api/v1/children_spec.rb:326:in `block (5 levels) in <top (required)>'
```

**Comment by arku** [comment]
This could happen if the [generated `approval`'s `effective_on` date](https://github.com/pieforproviders/pieforproviders/blob/develop/spec/factories/approvals.rb#L8) is exactly 1 year ago — the `expires_on` date is the current day and so the child has no current approvals.
